apiVersion: v1  
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
  spec:
  selector:
    app: my-app  # Correctement indenté ici
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer